# -*- coding: utf-8 -*-
"""PlantVillage_CNN_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i_AnwWvlxNhQdFtqAru4mqWAN4xFyg5O

# 🌿 Klasifikasi Penyakit Tanaman Tomat dengan Deep Learning (CNN)
## Dataset: PlantVillage — `gusliza/plantvillage`

**Nama :** [Gusli Yanza]  
**NIM  :** [8030230056]  
**Kelas:** [01PK6]  

---

### 📌 Deskripsi Proyek
Proyek ini membangun sistem klasifikasi otomatis penyakit daun tomat menggunakan dua pendekatan:
1. **Model 1 — CNN From Scratch** (Sequential)
2. **Model 2 — Transfer Learning** (MobileNetV2 + Fine-Tuning)

**10 Kelas Klasifikasi:**
| No | Kelas | Keterangan |
|---|---|---|
| 0 | bacterial_spot | Bercak Bakteri |
| 1 | early_blight | Hawar Awal |
| 2 | healthy | Sehat |
| 3 | late_blight | Hawar Akhir |
| 4 | leaf_mold | Jamur Daun |
| 5 | septoria_leaf_spot | Bercak Septoria |
| 6 | target_spot | Bercak Target |
| 7 | tomato_mosaic_virus | Virus Mosaik Tomat |
| 8 | tomato_yellow_leaf_curl_virus | Virus Keriting Kuning |
| 9 | two_spotted_spider_mite | Tungau Laba-laba |

---
**Runtime:** GPU (T4 / A100 direkomendasikan)

*DATASET:* https://www.kaggle.com/datasets/gusliza/plantvillage

## ✅ Tahap 0 — Verifikasi GPU & Setup Environment
"""

# Verifikasi GPU
import subprocess
result = subprocess.run(['nvidia-smi'], capture_output=True, text=True)
print(result.stdout if result.returncode == 0 else '⚠️  GPU tidak terdeteksi. Pastikan Runtime > Change Runtime Type > GPU!')

# Install dependencies
!pip install -q kagglehub tensorflow-addons

# Import semua library
import os
import json
import shutil
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from pathlib import Path
from collections import Counter
from PIL import Image

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import (
    EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
)
from tensorflow.keras.optimizers import Adam

from sklearn.metrics import (
    classification_report, confusion_matrix, ConfusionMatrixDisplay
)

import warnings
warnings.filterwarnings('ignore')

# Seed untuk reproduksibilitas
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

print(f'TensorFlow versi : {tf.__version__}')
print(f'GPU tersedia     : {tf.config.list_physical_devices("GPU")}')

"""---
## 📅 Tahap 1 — Persiapan Dataset

### 1.1 Download Dataset dari Kaggle
"""

import kagglehub

# Download dataset PlantVillage
path = kagglehub.dataset_download("gusliza/plantvillage")
print("Path dataset:", path)

# Eksplorasi struktur direktori dataset
BASE_PATH = Path(path)
print("Isi root dataset:")
for item in sorted(BASE_PATH.rglob('*')):
    if item.is_dir() and len(item.parts) - len(BASE_PATH.parts) <= 3:
        indent = '  ' * (len(item.parts) - len(BASE_PATH.parts))
        print(f"{indent}📁 {item.name}")

# Deteksi path split yang tersedia
DATASET_CLEAN = BASE_PATH / 'dataset_clean'
TRAIN_DIR     = DATASET_CLEAN / 'train'
VAL_DIR       = DATASET_CLEAN / 'validation'
TEST_DIR      = DATASET_CLEAN / 'test'

# Ambil nama kelas dari folder train
CLASS_NAMES = sorted([d.name for d in TRAIN_DIR.iterdir() if d.is_dir()])
NUM_CLASSES = len(CLASS_NAMES)

print(f"Jumlah kelas  : {NUM_CLASSES}")
print(f"Nama kelas    :")
for i, c in enumerate(CLASS_NAMES):
    print(f"  {i:2d}. {c}")

"""### 1.2 Eksplorasi & Visualisasi Dataset"""

def count_images(directory):
    """Hitung jumlah gambar per kelas dalam direktori."""
    counts = {}
    total  = 0
    for cls in CLASS_NAMES:
        cls_path = Path(directory) / cls
        if cls_path.exists():
            n = len(list(cls_path.glob('*.jpg')) +
                    list(cls_path.glob('*.jpeg')) +
                    list(cls_path.glob('*.png')))
            counts[cls] = n
            total += n
        else:
            counts[cls] = 0
    return counts, total

train_counts, train_total = count_images(TRAIN_DIR)
val_counts,   val_total   = count_images(VAL_DIR)
test_counts,  test_total  = count_images(TEST_DIR)
grand_total = train_total + val_total + test_total

# Ringkasan
df_dist = pd.DataFrame({
    'Kelas'     : CLASS_NAMES,
    'Train'     : [train_counts[c] for c in CLASS_NAMES],
    'Validation': [val_counts[c]   for c in CLASS_NAMES],
    'Test'      : [test_counts[c]  for c in CLASS_NAMES],
})
df_dist['Total'] = df_dist['Train'] + df_dist['Validation'] + df_dist['Test']

print("="*65)
print(f"  DISTRIBUSI DATASET — PlantVillage (Tomat)")
print("="*65)
print(df_dist.to_string(index=False))
print("-"*65)
print(f"  TOTAL   | {train_total:>6} | {val_total:>10} | {test_total:>4} | {grand_total:>6}")
print("="*65)
print(f"\n📊 Proporsi split  : Train {train_total/grand_total*100:.1f}% "
      f"| Val {val_total/grand_total*100:.1f}% "
      f"| Test {test_total/grand_total*100:.1f}%")

# Visualisasi distribusi kelas
fig, axes = plt.subplots(1, 2, figsize=(18, 6))

# Bar chart distribusi per split
x = np.arange(NUM_CLASSES)
w = 0.28
axes[0].bar(x - w, [train_counts[c] for c in CLASS_NAMES], w, label='Train',      color='#2196F3', alpha=0.85)
axes[0].bar(x,     [val_counts[c]   for c in CLASS_NAMES], w, label='Validation', color='#FF9800', alpha=0.85)
axes[0].bar(x + w, [test_counts[c]  for c in CLASS_NAMES], w, label='Test',       color='#4CAF50', alpha=0.85)
axes[0].set_xticks(x)
axes[0].set_xticklabels([c.replace('_', '\n') for c in CLASS_NAMES], fontsize=7)
axes[0].set_title('Distribusi Gambar per Kelas & Split', fontsize=13, fontweight='bold')
axes[0].set_ylabel('Jumlah Gambar')
axes[0].legend()
axes[0].grid(axis='y', alpha=0.3)

# Pie chart total per split
sizes  = [train_total, val_total, test_total]
labels = [f'Train\n{train_total:,}', f'Validation\n{val_total:,}', f'Test\n{test_total:,}']
colors = ['#2196F3', '#FF9800', '#4CAF50']
axes[1].pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%',
            startangle=90, textprops={'fontsize': 11})
axes[1].set_title(f'Proporsi Split Dataset\nTotal: {grand_total:,} gambar', fontsize=13, fontweight='bold')

plt.tight_layout()
plt.savefig('distribusi_dataset.png', dpi=150, bbox_inches='tight')
plt.show()
print("\n📌 Alasan pemilihan proporsi dataset:")
print("   Dataset sudah di-split oleh penyedia (split_manifest.csv).")
print("   Proporsi yang digunakan mengikuti pembagian resmi dataset (~80:10:10)")
print("   yang umum digunakan dalam penelitian computer vision untuk memastikan")
print("   model memiliki cukup data latih, sedangkan validasi & test memadai")
print("   untuk evaluasi generalisasi secara akurat.")

# Tampilkan contoh gambar dari setiap kelas
fig, axes = plt.subplots(2, 5, figsize=(20, 9))
axes = axes.flatten()

for i, cls in enumerate(CLASS_NAMES):
    cls_path = TRAIN_DIR / cls
    imgs = list(cls_path.glob('*.jpg')) + list(cls_path.glob('*.jpeg')) + list(cls_path.glob('*.png'))
    if imgs:
        img = Image.open(random.choice(imgs)).convert('RGB')
        axes[i].imshow(img)
        axes[i].set_title(cls.replace('_', '\n'), fontsize=8, fontweight='bold')
        axes[i].axis('off')

plt.suptitle('Contoh Gambar per Kelas — PlantVillage Tomato', fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('contoh_gambar.png', dpi=150, bbox_inches='tight')
plt.show()

"""### 1.3 Konfigurasi Global"""

# ============================================================
#   KONFIGURASI GLOBAL
# ============================================================
IMG_SIZE    = (224, 224)   # Resize semua gambar ke 128×128
BATCH_SIZE  = 32
EPOCHS_SCR  = 50           # Epoch max CNN from scratch
EPOCHS_TL   = 30           # Epoch max transfer learning (feature extraction)
EPOCHS_FT   = 20           # Epoch max fine-tuning
LR_SCR      = 1e-3         # Learning rate CNN scratch
LR_TL       = 1e-3         # Learning rate transfer learning
LR_FT       = 1e-5         # Learning rate fine-tuning (sangat kecil)

print(f"Ukuran Gambar  : {IMG_SIZE}")
print(f"Batch Size     : {BATCH_SIZE}")
print(f"Jumlah Kelas   : {NUM_CLASSES}")

"""### 1.4 Data Generator & Augmentasi"""

# ── Data Augmentasi untuk Training ──────────────────────────
train_datagen = ImageDataGenerator(
    rescale          = 1./255,
    rotation_range   = 30,
    width_shift_range= 0.2,
    height_shift_range=0.2,
    shear_range      = 0.15,
    zoom_range       = 0.2,
    horizontal_flip  = True,
    vertical_flip    = False,
    fill_mode        = 'nearest'
)

# ── Validasi & Test hanya rescale ────────────────────────────
val_test_datagen = ImageDataGenerator(rescale=1./255)

# ── Load Dataset ─────────────────────────────────────────────
def build_generators(img_size=IMG_SIZE, batch=BATCH_SIZE):
    train_gen = train_datagen.flow_from_directory(
        TRAIN_DIR, target_size=img_size, batch_size=batch,
        class_mode='categorical', shuffle=True, seed=SEED
    )
    val_gen = val_test_datagen.flow_from_directory(
        VAL_DIR, target_size=img_size, batch_size=batch,
        class_mode='categorical', shuffle=False
    )
    test_gen = val_test_datagen.flow_from_directory(
        TEST_DIR, target_size=img_size, batch_size=batch,
        class_mode='categorical', shuffle=False
    )
    return train_gen, val_gen, test_gen

train_gen, val_gen, test_gen = build_generators()

print(f"\nTrain   : {train_gen.samples:,} gambar")
print(f"Val     : {val_gen.samples:,} gambar")
print(f"Test    : {test_gen.samples:,} gambar")
print(f"\nClass indices: {train_gen.class_indices}")

# Visualisasi efek augmentasi
aug_check = ImageDataGenerator(
    rescale=1./255, rotation_range=30,
    width_shift_range=0.2, height_shift_range=0.2,
    zoom_range=0.2, horizontal_flip=True, fill_mode='nearest'
)

sample_cls = CLASS_NAMES[0]
sample_img_path = list((TRAIN_DIR / sample_cls).glob('*.jpg'))[0]
sample_arr = np.array(Image.open(sample_img_path).convert('RGB').resize(IMG_SIZE))[np.newaxis] / 255.

fig, axes = plt.subplots(2, 5, figsize=(18, 7))
axes[0, 0].imshow(sample_arr[0])
axes[0, 0].set_title('Original', fontweight='bold')
axes[0, 0].axis('off')

aug_gen = aug_check.flow(sample_arr * 255, batch_size=1)
for i, ax in enumerate(axes.flatten()[1:]):
    aug_img = next(aug_gen)[0]
    ax.imshow(aug_img)
    ax.set_title(f'Augmented #{i+1}')
    ax.axis('off')

plt.suptitle(f'Efek Data Augmentasi — Kelas: {sample_cls}', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('augmentasi.png', dpi=150, bbox_inches='tight')
plt.show()

"""---
## 🏗️ Tahap 2 — Eksperimen Arsitektur Model
### 2.1 Helper Functions
"""

def plot_training_history(history, title='Training History', save_name='history'):
    """Plot akurasi dan loss training vs validation."""
    fig, axes = plt.subplots(1, 2, figsize=(15, 5))

    # Akurasi
    axes[0].plot(history.history['accuracy'],     label='Train Accuracy',      color='#2196F3', linewidth=2)
    axes[0].plot(history.history['val_accuracy'], label='Validation Accuracy', color='#FF9800', linewidth=2, linestyle='--')
    axes[0].set_title(f'{title}\nAkurasi', fontweight='bold')
    axes[0].set_xlabel('Epoch')
    axes[0].set_ylabel('Accuracy')
    axes[0].legend()
    axes[0].grid(alpha=0.3)
    axes[0].set_ylim([0, 1.05])

    # Loss
    axes[1].plot(history.history['loss'],     label='Train Loss',      color='#F44336', linewidth=2)
    axes[1].plot(history.history['val_loss'], label='Validation Loss', color='#9C27B0', linewidth=2, linestyle='--')
    axes[1].set_title(f'{title}\nLoss', fontweight='bold')
    axes[1].set_xlabel('Epoch')
    axes[1].set_ylabel('Loss')
    axes[1].legend()
    axes[1].grid(alpha=0.3)

    plt.tight_layout()
    plt.savefig(f'{save_name}.png', dpi=150, bbox_inches='tight')
    plt.show()


def evaluate_model(model, test_gen, class_names, title='Model'):
    """Evaluasi lengkap: akurasi, confusion matrix, classification report."""
    test_gen.reset()
    preds  = model.predict(test_gen, verbose=0)
    y_pred = np.argmax(preds, axis=1)
    y_true = test_gen.classes

    loss, acc = model.evaluate(test_gen, verbose=0)
    print(f"\n{'='*55}")
    print(f"  EVALUASI — {title}")
    print(f"{'='*55}")
    print(f"  Test Loss    : {loss:.4f}")
    print(f"  Test Accuracy: {acc*100:.2f}%")
    print(f"{'='*55}")

    # Classification Report
    print("\nClassification Report:")
    print(classification_report(y_true, y_pred, target_names=class_names))

    # Confusion Matrix
    cm = confusion_matrix(y_true, y_pred)
    fig, ax = plt.subplots(figsize=(12, 10))
    disp = ConfusionMatrixDisplay(cm, display_labels=class_names)
    disp.plot(ax=ax, colorbar=True, cmap='Blues', xticks_rotation=45)
    ax.set_title(f'Confusion Matrix — {title}', fontsize=13, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'cm_{title.lower().replace(" ","_")}.png', dpi=150, bbox_inches='tight')
    plt.show()

    return loss, acc, y_true, y_pred


def analyze_fit(train_acc, val_acc, test_acc, model_name):
    """Analisis overfitting / underfitting / good fit."""
    gap = abs(train_acc - val_acc)
    print(f"\n📊 Analisis Kesesuaian Model — {model_name}")
    print(f"   Train Acc   : {train_acc*100:.2f}%")
    print(f"   Val Acc     : {val_acc*100:.2f}%")
    print(f"   Test Acc    : {test_acc*100:.2f}%")
    print(f"   Gap (|T-V|) : {gap*100:.2f}%")
    if train_acc < 0.80:
        status = '⚠️  UNDERFITTING — Model belum belajar dengan baik'
    elif gap > 0.10:
        status = '⚠️  OVERFITTING — Model terlalu hafal data training'
    else:
        status = '✅  GOOD FIT — Model generalisasi dengan baik'
    print(f"   Status      : {status}")
    return status

print('Helper functions siap ✅')

"""---
### 🔵 Model 1 — CNN From Scratch (Sequential)
"""

def build_cnn_scratch(input_shape=(128, 128, 3), num_classes=10):
    """
    Arsitektur CNN From Scratch:
    - 4 blok Conv2D + BatchNorm + MaxPool
    - GlobalAveragePooling2D
    - Dense + Dropout
    - Output Softmax
    """
    model = models.Sequential(name='CNN_Scratch')

    # ── Blok Konvolusi 1 ─────────────────────────────────────
    model.add(layers.Conv2D(32, (3,3), activation='relu', padding='same',
                            input_shape=input_shape))
    model.add(layers.BatchNormalization())
    model.add(layers.Conv2D(32, (3,3), activation='relu', padding='same'))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D((2,2)))
    model.add(layers.Dropout(0.25))

    # ── Blok Konvolusi 2 ─────────────────────────────────────
    model.add(layers.Conv2D(64, (3,3), activation='relu', padding='same'))
    model.add(layers.BatchNormalization())
    model.add(layers.Conv2D(64, (3,3), activation='relu', padding='same'))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D((2,2)))
    model.add(layers.Dropout(0.25))

    # ── Blok Konvolusi 3 ─────────────────────────────────────
    model.add(layers.Conv2D(128, (3,3), activation='relu', padding='same'))
    model.add(layers.BatchNormalization())
    model.add(layers.Conv2D(128, (3,3), activation='relu', padding='same'))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D((2,2)))
    model.add(layers.Dropout(0.30))

    # ── Blok Konvolusi 4 ─────────────────────────────────────
    model.add(layers.Conv2D(256, (3,3), activation='relu', padding='same'))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D((2,2)))
    model.add(layers.Dropout(0.30))

    # ── Classification Head ───────────────────────────────────
    model.add(layers.GlobalAveragePooling2D())
    model.add(layers.Dense(512, activation='relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.Dropout(0.50))
    model.add(layers.Dense(256, activation='relu'))
    model.add(layers.Dropout(0.40))
    model.add(layers.Dense(num_classes, activation='softmax'))

    return model

model_scratch = build_cnn_scratch(input_shape=(*IMG_SIZE, 3), num_classes=NUM_CLASSES)
model_scratch.summary()

# Compile Model 1
model_scratch.compile(
    optimizer = Adam(learning_rate=LR_SCR),
    loss      = 'categorical_crossentropy',
    metrics   = ['accuracy']
)

# ── Callbacks ────────────────────────────────────────────────
# EarlyStopping  : Hentikan training jika val_loss tidak membaik selama 10 epoch
#                  untuk mencegah overfitting dan menghemat waktu komputasi.
# ReduceLROnPlateau: Kurangi LR sebesar faktor 0.3 jika val_loss stagnan 5 epoch,
#                    membantu model 'kabur' dari local minima.
# ModelCheckpoint: Simpan bobot terbaik berdasarkan val_accuracy untuk memastikan
#                  kita selalu mendapatkan model terbaik.

callbacks_scratch = [
    EarlyStopping(
        monitor='val_loss', patience=10,
        restore_best_weights=True, verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss', factor=0.3,
        patience=5, min_lr=1e-7, verbose=1
    ),
    ModelCheckpoint(
        'best_scratch.keras', monitor='val_accuracy',
        save_best_only=True, verbose=0
    )
]

print("Model 1 — CNN Scratch siap dilatih ✅")

# Training Model 1
print("🚀 Melatih CNN From Scratch...")
history_scratch = model_scratch.fit(
    train_gen,
    epochs          = EPOCHS_SCR,
    validation_data = val_gen,
    callbacks       = callbacks_scratch,
    verbose         = 1
)
print("\n✅ Training CNN Scratch selesai!")

# Visualisasi training history Model 1
plot_training_history(history_scratch,
                      title='CNN From Scratch',
                      save_name='history_scratch')

# Evaluasi Model 1
loss_s, acc_s, yt_s, yp_s = evaluate_model(
    model_scratch, test_gen, CLASS_NAMES, title='CNN From Scratch'
)

# Ambil akurasi epoch terakhir
best_train_acc_s = max(history_scratch.history['accuracy'])
best_val_acc_s   = max(history_scratch.history['val_accuracy'])
analyze_fit(best_train_acc_s, best_val_acc_s, acc_s, 'CNN From Scratch')

"""---
### 🟠 Model 2 — Transfer Learning (MobileNetV2)
#### Tahap 1: Feature Extraction (Semua Layer Beku)
"""

def build_transfer_learning(input_shape=(128, 128, 3), num_classes=10, trainable=False):
    """
    Transfer Learning MobileNetV2 + Classification Head:
    - Base: MobileNetV2 (imagenet), layer beku untuk feature extraction
    - Head: GlobalAveragePooling2D → Dense(256) → Dropout → Output
    """
    base = MobileNetV2(
        input_shape = input_shape,
        include_top = False,
        weights     = 'imagenet'
    )
    base.trainable = trainable  # False = freeze semua layer

    inputs = keras.Input(shape=input_shape)
    x = base(inputs, training=False)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dense(256, activation='relu')(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.40)(x)
    outputs = layers.Dense(num_classes, activation='softmax')(x)

    model = keras.Model(inputs, outputs, name='MobileNetV2_TL')
    return model, base

model_tl, base_model = build_transfer_learning(
    input_shape=(*IMG_SIZE, 3), num_classes=NUM_CLASSES, trainable=False
)

# Info layer
total_params    = model_tl.count_params()
trainable_params = sum([tf.size(w).numpy() for w in model_tl.trainable_weights])
frozen_params    = total_params - trainable_params

model_tl.summary()
print(f"\nTotal parameter   : {total_params:,}")
print(f"Trainable (head)  : {trainable_params:,}")
print(f"Frozen (base)     : {frozen_params:,}")

# Compile Tahap 1 — Feature Extraction
model_tl.compile(
    optimizer = Adam(learning_rate=LR_TL),
    loss      = 'categorical_crossentropy',
    metrics   = ['accuracy']
)

callbacks_tl = [
    EarlyStopping(
        monitor='val_loss', patience=8,
        restore_best_weights=True, verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss', factor=0.3,
        patience=4, min_lr=1e-8, verbose=1
    ),
    ModelCheckpoint(
        'best_tl_stage1.keras', monitor='val_accuracy',
        save_best_only=True, verbose=0
    )
]

print("🚀 Training Transfer Learning — Feature Extraction...")
history_tl = model_tl.fit(
    train_gen,
    epochs          = EPOCHS_TL,
    validation_data = val_gen,
    callbacks       = callbacks_tl,
    verbose         = 1
)
print("\n✅ Feature Extraction selesai!")

# Visualisasi history Feature Extraction
plot_training_history(history_tl,
                      title='MobileNetV2 — Feature Extraction',
                      save_name='history_tl_stage1')

"""#### 🔥 Tahap 2 (BONUS): Fine-Tuning — Buka 30 Layer Terakhir"""

# Fine-Tuning: buka 30 layer terakhir base model
base_model.trainable = True
FINE_TUNE_AT = len(base_model.layers) - 30

for layer in base_model.layers[:FINE_TUNE_AT]:
    layer.trainable = False

# Hitung ulang parameter
trainable_ft = sum([tf.size(w).numpy() for w in model_tl.trainable_weights])
print(f"Layer base model total    : {len(base_model.layers)}")
print(f"Layer yang dibuka (unfrozen): 30 layer terakhir (dari index {FINE_TUNE_AT})")
print(f"Trainable parameter sekarang: {trainable_ft:,}")

# Compile ulang dengan LR sangat kecil
model_tl.compile(
    optimizer = Adam(learning_rate=LR_FT),
    loss      = 'categorical_crossentropy',
    metrics   = ['accuracy']
)

callbacks_ft = [
    EarlyStopping(
        monitor='val_loss', patience=8,
        restore_best_weights=True, verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss', factor=0.3,
        patience=4, min_lr=1e-9, verbose=1
    ),
    ModelCheckpoint(
        'best_tl_finetune.keras', monitor='val_accuracy',
        save_best_only=True, verbose=0
    )
]

print(f"\n🚀 Fine-Tuning dengan LR = {LR_FT}...")
history_ft = model_tl.fit(
    train_gen,
    epochs          = EPOCHS_FT,
    validation_data = val_gen,
    callbacks       = callbacks_ft,
    verbose         = 1
)
print("\n✅ Fine-Tuning selesai!")

# Visualisasi history Fine-Tuning
plot_training_history(history_ft,
                      title='MobileNetV2 — Fine-Tuning',
                      save_name='history_ft')

# Plot gabungan Feature Extraction + Fine-Tuning
total_epochs = len(history_tl.history['accuracy']) + len(history_ft.history['accuracy'])
acc_all      = history_tl.history['accuracy'] + history_ft.history['accuracy']
val_acc_all  = history_tl.history['val_accuracy'] + history_ft.history['val_accuracy']

fig, ax = plt.subplots(figsize=(12, 5))
ax.plot(acc_all,     label='Train Accuracy', color='#2196F3', linewidth=2)
ax.plot(val_acc_all, label='Val Accuracy',   color='#FF9800', linewidth=2, linestyle='--')
ax.axvline(x=len(history_tl.history['accuracy']),
           color='red', linestyle=':', linewidth=1.5, label='Mulai Fine-Tuning')
ax.set_title('MobileNetV2: Feature Extraction → Fine-Tuning', fontweight='bold', fontsize=13)
ax.set_xlabel('Epoch')
ax.set_ylabel('Accuracy')
ax.legend()
ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('history_combined.png', dpi=150, bbox_inches='tight')
plt.show()

"""---
## 📈 Tahap 3 — Evaluasi & Penyimpanan Model

### 3.1 Evaluasi Lengkap Kedua Model
"""

# Evaluasi Model 2 (Transfer Learning + Fine-Tuning)
loss_tl, acc_tl, yt_tl, yp_tl = evaluate_model(
    model_tl, test_gen, CLASS_NAMES, title='MobileNetV2 Fine-Tuned'
)

best_train_acc_tl = max(history_ft.history['accuracy'])
best_val_acc_tl   = max(history_ft.history['val_accuracy'])
analyze_fit(best_train_acc_tl, best_val_acc_tl, acc_tl, 'MobileNetV2 Fine-Tuned')

"""### 3.2 Perbandingan Model"""

# Tabel perbandingan
comparison_data = {
    'Model'         : ['CNN From Scratch', 'MobileNetV2 Fine-Tuned'],
    'Test Accuracy' : [f'{acc_s*100:.2f}%', f'{acc_tl*100:.2f}%'],
    'Test Loss'     : [f'{loss_s:.4f}', f'{loss_tl:.4f}'],
    'Total Params'  : [
        f"{model_scratch.count_params():,}",
        f"{model_tl.count_params():,}"
    ],
    'Best Val Acc'  : [
        f"{max(history_scratch.history['val_accuracy'])*100:.2f}%",
        f"{max(history_ft.history['val_accuracy'])*100:.2f}%"
    ]
}

df_compare = pd.DataFrame(comparison_data)
print("\n" + "="*70)
print("  PERBANDINGAN PERFORMA MODEL")
print("="*70)
print(df_compare.to_string(index=False))
print("="*70)

# Bar chart perbandingan
models_names = ['CNN\nFrom Scratch', 'MobileNetV2\nFine-Tuned']
accs = [acc_s * 100, acc_tl * 100]

fig, ax = plt.subplots(figsize=(8, 5))
bars = ax.bar(models_names, accs,
              color=['#2196F3', '#FF9800'], width=0.5,
              edgecolor='white', linewidth=1.5)
ax.set_ylim([80, 100])
ax.set_ylabel('Test Accuracy (%)', fontsize=12)
ax.set_title('Perbandingan Test Accuracy\nCNN Scratch vs MobileNetV2', fontweight='bold', fontsize=13)
ax.axhline(y=90, color='red', linestyle='--', linewidth=1.5, label='Target 90%')
ax.legend()
ax.grid(axis='y', alpha=0.3)

for bar, acc in zip(bars, accs):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.2,
            f'{acc:.2f}%', ha='center', va='bottom', fontsize=12, fontweight='bold')

plt.tight_layout()
plt.savefig('perbandingan_model.png', dpi=150, bbox_inches='tight')
plt.show()

"""### 3.3 Ekspor Model — 3 Format"""

import os
import shutil

# Gunakan model terbaik
BEST_MODEL = model_tl
MODEL_NAME = "plantvillage_tomato_classifier"

os.makedirs("exports", exist_ok=True)

# ── FORMAT 1: TensorFlow SavedModel ──────────────────────
SAVEDMODEL_PATH = f"exports/{MODEL_NAME}_savedmodel"

# Hapus ekspor lama jika cell dijalankan ulang
if os.path.exists(SAVEDMODEL_PATH):
    shutil.rmtree(SAVEDMODEL_PATH)

# Keras 3: gunakan export(), bukan save()
BEST_MODEL.export(SAVEDMODEL_PATH)

print("✅ Format 1 — TensorFlow SavedModel berhasil disimpan:")
print(f"   {SAVEDMODEL_PATH}/")

# ── FORMAT 2: TensorFlow Lite (.tflite) ─────────────────────
converter = tf.lite.TFLiteConverter.from_saved_model(SAVEDMODEL_PATH)
converter.optimizations = [tf.lite.Optimize.DEFAULT]  # Quantization ringan
tflite_model = converter.convert()

TFLITE_PATH = f'exports/{MODEL_NAME}.tflite'
with open(TFLITE_PATH, 'wb') as f:
    f.write(tflite_model)

size_mb = os.path.getsize(TFLITE_PATH) / (1024 * 1024)
print(f"✅ Format 2 — TensorFlow Lite: {TFLITE_PATH} ({size_mb:.2f} MB)")

# ── FORMAT 3: TensorFlow.js ──────────────────────────────────
!pip install -q tensorflowjs

TFJS_PATH = f'exports/{MODEL_NAME}_tfjs'
!tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_format=tfjs_graph_model \
    --signature_name=serving_default \
    --saved_model_tags=serve \
    {SAVEDMODEL_PATH} {TFJS_PATH}

print(f"\n✅ Format 3 — TensorFlow.js: {TFJS_PATH}/")

# Simpan class names untuk inferensi
with open('exports/class_names.json', 'w') as f:
    json.dump({'class_names': CLASS_NAMES}, f, indent=2)

print("✅ class_names.json tersimpan")

# Ringkasan file ekspor
print("\n📦 FILE EKSPOR:")
for root, dirs, files in os.walk('exports'):
    level = root.replace('exports', '').count(os.sep)
    indent = '  ' * level
    print(f"{indent}📁 {os.path.basename(root)}/")
    sub_indent = '  ' * (level + 1)
    for file in files:
        fpath = os.path.join(root, file)
        size  = os.path.getsize(fpath) / 1024
        print(f"{sub_indent}📄 {file} ({size:.1f} KB)")

"""---
## 🔍 Inferensi Model — Uji pada Gambar Baru
"""

def predict_image(img_path, model, class_names, img_size=IMG_SIZE, top_k=3):
    """
    Inferensi satu gambar dan tampilkan:
    - Gambar uji
    - Label asli (dari nama folder)
    - Hasil prediksi & probabilitas top-k
    """
    img = Image.open(img_path).convert('RGB').resize(img_size)
    arr = np.array(img) / 255.
    arr = np.expand_dims(arr, axis=0)

    probs = model.predict(arr, verbose=0)[0]
    top_indices = np.argsort(probs)[::-1][:top_k]

    true_label = Path(img_path).parent.name
    pred_label = class_names[top_indices[0]]
    pred_prob  = probs[top_indices[0]]

    return img, true_label, pred_label, pred_prob, top_indices, probs


# Ambil 10 gambar acak dari test set (1 per kelas)
test_samples = []
for cls in CLASS_NAMES:
    cls_path = TEST_DIR / cls
    imgs = list(cls_path.glob('*.jpg')) + list(cls_path.glob('*.jpeg')) + list(cls_path.glob('*.png'))
    if imgs:
        test_samples.append(random.choice(imgs))

print(f"Jumlah gambar uji: {len(test_samples)}")

# Inferensi & visualisasi
fig, axes = plt.subplots(2, 5, figsize=(22, 10))
axes = axes.flatten()

correct = 0
for i, img_path in enumerate(test_samples):
    img, true_lbl, pred_lbl, pred_prob, top_idx, probs = predict_image(
        img_path, BEST_MODEL, CLASS_NAMES
    )
    is_correct = (true_lbl == pred_lbl)
    correct += int(is_correct)
    color = '#2ecc71' if is_correct else '#e74c3c'
    icon  = '✅' if is_correct else '❌'

    axes[i].imshow(img)
    axes[i].set_title(
        f"{icon} True: {true_lbl.replace('_',' ')}\n"
        f"Pred: {pred_lbl.replace('_',' ')} ({pred_prob*100:.1f}%)",
        fontsize=7.5, color=color, fontweight='bold'
    )
    axes[i].axis('off')

plt.suptitle(
    f'Inferensi Model — {correct}/{len(test_samples)} Benar '
    f'(Akurasi Inferensi: {correct/len(test_samples)*100:.0f}%)',
    fontsize=14, fontweight='bold', y=1.01
)
plt.tight_layout()
plt.savefig('inferensi_hasil.png', dpi=150, bbox_inches='tight')
plt.show()
print(f"\n📊 Hasil Inferensi: {correct}/{len(test_samples)} prediksi benar")

# Detail probabilitas tiap prediksi
print("\n📋 Detail Probabilitas Prediksi:")
print("-"*70)
for i, img_path in enumerate(test_samples):
    img, true_lbl, pred_lbl, pred_prob, top_idx, probs = predict_image(
        img_path, BEST_MODEL, CLASS_NAMES, top_k=3
    )
    ok = '✅' if true_lbl == pred_lbl else '❌'
    print(f"{ok} [{i+1:2d}] True: {true_lbl:<35} | Pred: {pred_lbl:<35} | {pred_prob*100:6.2f}%")

# Inferensi menggunakan TFLite model
print("🔍 Inferensi menggunakan model TFLite...\n")

interpreter = tf.lite.Interpreter(model_path=TFLITE_PATH)
interpreter.allocate_tensors()
input_details  = interpreter.get_input_details()
output_details = interpreter.get_output_details()

def predict_tflite(img_path, interpreter, class_names, img_size=IMG_SIZE):
    img = Image.open(img_path).convert('RGB').resize(img_size)
    arr = np.array(img, dtype=np.float32) / 255.
    arr = np.expand_dims(arr, axis=0)
    interpreter.set_tensor(input_details[0]['index'], arr)
    interpreter.invoke()
    output = interpreter.get_tensor(output_details[0]['index'])[0]
    pred_idx   = np.argmax(output)
    pred_label = class_names[pred_idx]
    pred_prob  = output[pred_idx]
    return pred_label, pred_prob

print(f"{'Gambar':<5} | {'True Label':<40} | {'TFLite Prediction':<40} | {'Prob':>6}")
print("-"*100)
tflite_correct = 0
for i, img_path in enumerate(test_samples[:5]):
    true_lbl = Path(img_path).parent.name
    pred_lbl, pred_prob = predict_tflite(img_path, interpreter, CLASS_NAMES)
    ok = '✅' if true_lbl == pred_lbl else '❌'
    tflite_correct += int(true_lbl == pred_lbl)
    print(f"{ok} #{i+1:2d} | {true_lbl:<40} | {pred_lbl:<40} | {pred_prob*100:5.2f}%")

print(f"\nTFLite Accuracy (5 sampel): {tflite_correct}/5")

"""---
## 📊 Ringkasan Akhir & Kesimpulan
"""

print("="*70)
print("  RINGKASAN AKHIR PROYEK")
print("  Klasifikasi Penyakit Tomat — PlantVillage")
print("="*70)
print(f"  Dataset Total     : {grand_total:,} gambar, {NUM_CLASSES} kelas")
print(f"  Ukuran Input      : {IMG_SIZE}")
print(f"  Batch Size        : {BATCH_SIZE}")
print()
print(f"  [Model 1 - CNN Scratch]")
print(f"    Test Accuracy   : {acc_s*100:.2f}%")
print(f"    Test Loss       : {loss_s:.4f}")
print(f"    Status          : {'✅ Target Tercapai' if acc_s >= 0.90 else '⚠️  Perlu Tuning'}")
print()
print(f"  [Model 2 - MobileNetV2 Fine-Tuned]")
print(f"    Test Accuracy   : {acc_tl*100:.2f}%")
print(f"    Test Loss       : {loss_tl:.4f}")
print(f"    Status          : {'✅ Target Tercapai' if acc_tl >= 0.90 else '⚠️  Perlu Tuning'}")
print()
print(f"  Model Ekspor (di folder exports/):")
print(f"    ✅ TensorFlow SavedModel")
print(f"    ✅ TensorFlow Lite (.tflite)")
print(f"    ✅ TensorFlow.js")
print("="*70)

print("""
📝 KESIMPULAN:

1. CNN From Scratch berhasil mempelajari fitur-fitur visual penyakit
   tanaman tomat dari nol menggunakan arsitektur 4-blok konvolusi,
   BatchNormalization, Dropout, dan GlobalAveragePooling.

2. MobileNetV2 dengan Transfer Learning + Fine-Tuning memanfaatkan
   representasi fitur ImageNet yang sudah kaya, sehingga konvergensi
   lebih cepat dan akurasi lebih tinggi dengan parameter yang lebih
   efisien berkat arsitektur depthwise separable convolution.

3. Penggunaan callback (EarlyStopping, ReduceLROnPlateau, ModelCheckpoint)
   terbukti efektif mencegah overfitting dan mengoptimalkan proses
   training secara otomatis.

4. Data augmentasi (rotasi, flip, zoom, shift) meningkatkan kemampuan
   generalisasi model terhadap variasi kondisi pengambilan gambar di lapangan.
""")

# Zip semua file output
import zipfile

output_files = [
    'distribusi_dataset.png', 'contoh_gambar.png', 'augmentasi.png',
    'history_scratch.png', 'cm_cnn_from_scratch.png',
    'history_tl_stage1.png', 'history_ft.png', 'history_combined.png',
    'cm_mobilenetv2_fine-tuned.png', 'perbandingan_model.png',
    'inferensi_hasil.png',
    'best_scratch.keras', 'best_tl_finetune.keras'
]

with zipfile.ZipFile('hasil_proyek_plantvillage.zip', 'w', zipfile.ZIP_DEFLATED) as zf:
    for f in output_files:
        if os.path.exists(f):
            zf.write(f)
    # Tambahkan folder exports
    for root, dirs, files in os.walk('exports'):
        for file in files:
            zf.write(os.path.join(root, file))

print("✅ Semua file dikemas dalam: hasil_proyek_plantvillage.zip")

# Download langsung di Colab
try:
    from google.colab import files
    files.download('hasil_proyek_plantvillage.zip')
    print("📥 Download dimulai...")
except:
    print("ℹ️  Jalankan di Colab untuk auto-download.")